spring:
  application:
    name: foodsocial-api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/circledb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: thecirclepostgres

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false

  http:
    encoding:
      charset: UTF-8
      force: true

  data:
    web:
      pageable:
        default-page-size: 10

security:
  encoding-strength: 256

app:
  storage:
    path: /opt/storage/the-circle/

  security:
    jwt:
      secret: z$C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$B&E)H+MbQeThWmZq4t
      signing-algorithm: HS512
      token-issuer: food-social
      token-audience: food-social-network