spring:
  application:
    name: foodsocial-api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false

  http:
    encoding:
      charset: UTF-8
      force: true

  data:
    web:
      pageable:
        default-page-size: 10

security:
  encoding-strength: 256

# TODO: Remove this when AWS S3 fully implemented
app:
  storage:
    path: /opt/storage/food-social/

  security:
    jwt:
      secret: ${JWT_SECRET:KFEiqnPK8B+GW3zo93H0LGrdAdzejEs8I6KawgpG/VP6rqOEaooGTKdHqgG3hirXI/i7PKmzxKGd1GAgL6AqcqloCqEINPgJDRVakpoCY7Dpqm0dnru0vz2JnRpwBs/1N4Ghljhxx06j/twy6BmJUwqv8Mi+YY4jVWOZTyLIaPvOtDeyiTTkIspJhhLD+cLxSkxKhhD6w5gXQ0qiZXwpzkxr4qBHNDBxkpCOTw==}
      signing-algorithm: HS512
      token-issuer: food-social
      token-audience: food-social-network

cloud:
  aws:
    stack:
      auto: false
    credentials:
      instanceProfile: false
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      auto: false
      static: ${AWS_REGION}