name: "API Deploy to Heroku"

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'agateownz-social-network-api'
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: 'backend'
