name: "API Deploy to Heroku"

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  verify:
    name: "Run Checkstyle & Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Verify
      working-directory: backend
      run: mvn -B verify
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

  build:
    name: Deploy
    needs: verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'agateownz-social-network-api'
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: 'backend'
