name: "API Deploy to Heroku"

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/api-deploy.yml'

jobs:
  verify:
    name: "Run Checkstyle & Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Verify
      working-directory: backend
      run: mvn -B verify
    - name: Codecov report
      uses: codecov/codecov-action@v1.0.7
      with:
        fail_ci_if_error: true

  build:
    name: Deploy
    needs: verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_BACKEND }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: 'backend'
