name: "Front Deploy to Heroku"

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  lint:
    name: "Run Lint"
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache local npm repository
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
        working-directory: frontend
      - name: Run Lint
        run: npm run lint
        working-directory: frontend

  build:
    name: Deploy
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'agateownz-social-network-app'
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: 'frontend'
